# This is a configuration file for the zizmor action defined in .github/workflows/zizmor.yaml

rules:
  # Disable the rule requiring all actions be pinned to a specific hash
  unpinned-uses:
    config:
      policies:
        "*": any
