name: Run All Live Tests

# Runs live tests that connect to the Signet network.
# Scheduled weekly and can be triggered manually.

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0' # Once per week

permissions: {}

jobs:
  swift-tests:
    name: "Test iOS library"
    runs-on: macos-14
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Build Swift package"
        working-directory: bdk-swift
        run: bash ./build-xcframework.sh

      - name: "Run live Swift tests"
        working-directory: bdk-swift
        run: swift test
