name: Publish bdk-android to Maven Central

# Publishes the bdk-android library to Maven Central repository.
# Builds the Android library with native components and signs + uploads the artifacts.
# Manual workflow that requires proper Maven Central credentials and PGP signing keys.
# Note: The default Android NDK on the ubuntu-24.04 image is 25.2.9519653.

on: [workflow_dispatch]

permissions: {}

jobs:
  publish:
    name: "Publish library"
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: bdk-android
    
    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Build bdk-android library"
        run: bash ./scripts/build-linux-x86_64.sh

      - name: "Publish to Maven Central"
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.PGP_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
