name: Test Android

# Tests the Android bindings for bdk-ffi on an Android emulator.
# Builds Rust binaries, sets up Android emulator, and runs the connected tests.

on:
  workflow_dispatch:
  push:
    paths:
      - "bdk-ffi/**"
      - "bdk-android/**"
  pull_request:
    paths:
      - "bdk-ffi/**"
      - "bdk-android/**"

permissions: {}

jobs:
  test:
    name: "Test Android library"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout PR branch"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Set up Android SDK"
        uses: android-actions/setup-android@v3

      - name: "Set up Android NDK"
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c

      - name: "Set up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Build Android library"
        run: |
          cd bdk-android
          bash ./scripts/build-linux-x86_64.sh

      - name: "Enable KVM"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Run Android connected tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: cd bdk-android && ./gradlew connectedAndroidTest --console=plain
