name: Trigger External Bindings Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci/python-workflow
    paths:
      - 'bdk-ffi/**'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:    
      # Trigger trigger-bdk-jvm-test workflow in bdk-jvm repository
      - name: Trigger tests in bdk-jvm repository
        if: ${{ github.ref_name == 'master' }}
        env:
          BDK_JVM_ACCESS_TOKEN: ${{ secrets.BDK_JVM_ACCESS_TOKEN }}
        run: |
          curl --silent --show-error \
            --output /tmp/resp.txt \
            --write-out "HTTP Status: %{http_code}\n" \
            --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer $BDK_JVM_ACCESS_TOKEN" \
            --data '{"event_type":"trigger-bdk-jvm-test"}' \
            https://api.github.com/repos/bitcoindevkit/bdk-jvm/dispatches
          echo "Response body:"
          if [ -s /tmp/resp.txt ]; then
            jq . /tmp/resp.txt || cat /tmp/resp.txt
          else
            echo "(empty)"
          fi

      # Trigger trigger-bdk-python-test workflow in bdk-python repository
      - name: Trigger tests in bdk-python repository
        if: ${{ github.ref_name == 'master' }}
        env:
          BDK_PYTHON_ACCESS_TOKEN: ${{ secrets.BDK_PYTHON_ACCESS_TOKEN }}
        run: |
          curl --silent --show-error \
            --output /tmp/resp_python.txt \
            --write-out "HTTP Status: %{http_code}\n" \
            --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer $BDK_PYTHON_ACCESS_TOKEN" \
            --data '{"event_type":"trigger-bdk-python-test"}' \
            https://api.github.com/repos/bitcoindevkit/bdk-python/dispatches
          echo "Response body:"
          if [ -s /tmp/resp_python.txt ]; then
            jq . /tmp/resp_python.txt || cat /tmp/resp_python.txt
          else
            echo "(empty)"
          fi
